---
title: "topic5:Application of hotelling T^2"
author: "shubhangi jadhav_2405"
date: "2025-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#one sample t_2 test
Q1 x~N5(mu,sigma)
```{r}
rm(list=ls())
library(MASS)
library(Matrix)
set.seed(123)
p=5
n=20
m=c(4.32,14.01,1.95,2.17,2.45)
mo=c(5,15,2,3,2)
S=matrix(c(4.308,1.683,1.803,2.155,-0.253,
           1.683,1.768,0.588,0.177,0.176,
           1.803,0.588,0.81,1.065,-0.158,
           2.155,0.177,1.065,1.970,-0.357,
           -0.253,0.176,-0.158,-0.357,0.504),nrow=5)
alpha=0.05

X=t(mvrnorm(n,m,S))
x_bar=rowMeans(X)
s_hat=cov(t(X))
T_2 = n*t(x_bar-mo)%*%solve(s_hat)%*%(x_bar-mo)
F=((n-p)*T_2)/(p*(n-1))
p_value=1-pf(F,p,(n-p))
ifelse(p_value<alpha,"reject Ho","we fail to reject Ho")


cat("T_2_statistic is :\n");print(T_2)

cat("F_statistic is: \n");print(F)

cat("p_value is: \n");print(p_value)

cat("reject Ho :\n")





```
# Q2.x~N4(mu,sigma)
```{r}
library(MASS)
library(Matrix)
set.seed(123)
p=4
n=30
m=c(6.833,7.033,5.967,4.91)
mo=c(6,7,5,4)
S=matrix(c(0.606,0.262,0.060,0.161,
           0.262,0.637,0.173,0.143,
           0.060,0.173,0.810,0.029,
           0.161,0.143,0.029,0.306),nrow=4)
alpha=0.05

X=t(mvrnorm(n,m,S))
x_bar=rowMeans(X)
s_hat=cov(t(X))
T_2=n*t((x_bar-mo))%*%solve(s_hat)%*%(x_bar-mo)
F=((n-p)*T_2)/(p*(n-1))
p_value=1-pf(F,p,n-p)
ifelse(p_value<alpha,"reject Ho","we fail to reject Ho")


cat("T_2_statistic is :\n");print(T_2)

cat("F_statistic is: \n");print(F)

cat("p_value is: \n");print(p_value)

cat("reject Ho :\n")


```

#tow sample  T_2 for
```{r}
rm(list=ls())
set.seed(123)
p=4
alpha=0.01
data(iris)
X=t(subset(iris, Species == "setosa")[, 1:4])
Y=t(subset(iris, Species == "versicolor")[, 1:4])
n1=ncol(X)
n2=ncol(Y)
n=n1+n2

x_bar=rowMeans(X)
y_bar=rowMeans(Y)
s1=cov(t(X))
s2=cov(t(Y))
a=((n1-1)*s1)+((n2-1)*s2)
s_pooled=a/(n1+n2-2)

D_2=(t(x_bar-y_bar))%*%solve(s_pooled)%*%(x_bar-y_bar)
T_2=(n1*n2*D_2)/n
b=(n-p-1)*T_2
F=b/(p*(n-2))
p_value=1-pf(F,p,n-p-1)
ifelse(p_value<alpha,"reject Ho","we fail to reject Ho")

cat("s_pooled is :\n");print(s_pooled)
cat("D_2_statistic is :\n");print(D_2)
cat("T_2_statistic is :\n");print(T_2)
cat("F_statistic is: \n");print(F)
cat("p_value is: \n");print(p_value)
cat("reject Ho :\n")

```
```{r}
rm(list=ls())
set.seed(123)
p=4
alpha=0.05
data(iris)
X=t(subset(iris, Species == "virginica")[, 1:4])
Y=t(subset(iris, Species == "versicolor")[, 1:4])
n1=ncol(X)
n2=ncol(Y)
n=n1+n2

x_bar=rowMeans(X)
y_bar=rowMeans(Y)
s1=cov(t(X))
s2=cov(t(Y))
a=((n1-1)*s1)+((n2-1)*s2)
s_pooled=a/(n1+n2-2)

D_2=(t(x_bar-y_bar))%*%solve(s_pooled)%*%(x_bar-y_bar)
T_2=(n1*n2*D_2)/n
b=(n-p-1)*T_2
F=b/(p*(n-2))
p_value=1-pf(F,p,n-p-1)
ifelse(p_value<alpha,"reject Ho","we fail to reject Ho")

cat("s_pooled is :\n");print(s_pooled)
cat("D_2_statistic is :\n");print(D_2)
cat("T_2_statistic is :\n");print(T_2)
cat("F_statistic is: \n");print(F)
cat("p_value is: \n");print(p_value)
cat("reject Ho :\n")

```
```{r}
rm(list=ls())
set.seed(123)
p=4
alpha=0.05
data(iris)
X=t(subset(iris, Species == "virginica")[, 1:4])
Y=t(subset(iris, Species == "setosa")[, 1:4])
n1=ncol(X)
n2=ncol(Y)
n=n1+n2

x_bar=rowMeans(X)
y_bar=rowMeans(Y)
s1=cov(t(X))
s2=cov(t(Y))
a=((n1-1)*s1)+((n2-1)*s2)
s_pooled=a/(n1+n2-2)

D_2=(t(x_bar-y_bar))%*%solve(s_pooled)%*%(x_bar-y_bar)
T_2=(n1*n2*D_2)/n
b=(n-p-1)*T_2
F=b/(p*(n-2))
p_value=1-pf(F,p,n-p-1)
ifelse(p_value<alpha,"reject Ho","we fail to reject Ho")

cat("s_pooled is :\n");print(s_pooled)
cat("D_2_statistic is :\n");print(D_2)
cat("T_2_statistic is :\n");print(T_2)
cat("F_statistic is: \n");print(F)
cat("p_value is: \n");print(p_value)
cat("reject Ho :\n")
```
# Q.3
```{r}
rm(list=ls())
p=4
alpha=0.05
x_bar=c(2.46,4.46,3.09,2.36,3.27)
y_bar=c(1.51,2.26,1.87,1.43,2)
n1=11
n2=35
n=n1+n2
s_pooled=matrix(c(1.0789,0.3659,0.4910,0.3061,0.6054,
                  0.3659,2.1685,0.7898,0.6892,0.9690,
                  0.4910,0.7898,1.6466,0.5307,0.9256,
                  0.3061,0.6892,0.5307,0.5708,0.5207,
                  0.6054,0.9690,0.9256,0.5207,1.0950),nrow = 5)
D_2=(t(x_bar-y_bar))%*%solve(s_pooled)%*%(x_bar-y_bar)
T_2=(n1*n2*D_2)/n
b=(n-p-1)*T_2
F=b/(p*(n-2))
p_value=1-pf(F,p,n-p-1)
ifelse(p_value<alpha,"reject Ho","we fail to reject Ho")

cat("s_pooled is :\n");print(s_pooled)
cat("D_2_statistic is :\n");print(D_2)
cat("T_2_statistic is :\n");print(T_2)
cat("F_statistic is: \n");print(F)
cat("p_value is: \n");print(p_value)
cat("reject Ho :\n")

```

