---
title: "topic_2:Model sampling from conditional MVD and its parameter estimation"
author: "shubhangi jadhav_2405"
date: "2025-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Q.1
```{r}
# a)
m=c(260,231,222)
S=matrix(c(2276,1508,813,
         1508,2206,1349,
         813,1349,1865),nrow=3)
l=c(1,-1,0)
m_1=t(l)%*%m
m_1
s_1=t(l)%*%S%*%l
s_1

#b)
x2=225
p=3
q=2

m1=m[1:q]
m2=m[(q+1):p]
s11=S[1:q,1:q]
s12=S[1:q,(q+1):p]
s22=S[(q+1):p,(q+1):p]
s21=t(s12)
s22_inv=solve(s22)

cm=m1+s12%*%s22_inv%*%(x2-m2)
cm=as.vector(cm)
cm
cs=s11-s12%*%s22_inv%*%s21
cs=as.matrix(cs)
cs
```

#Q2
```{r}
library(MASS)
#a)
set.seed(123)
m=c(4,3,2,1)
S=matrix(c(3,0,2,2,
           0,1,1,0,
           2,1,9,-2,
           2,0,-2,4
           ),nrow =4,byrow =T)
p=4
q=2
n=150

x2=c(3,2)
m1=m[1:q]
m2=m[(q+1):p]
s11=S[1:q,1:q]
s12=S[1:q,(q+1):p]
s22=S[(q+1):p,(q+1):p]
s21=t(s12)
s22_inv=solve(s22)

cm=m1+s12%*%s22_inv%*%(x2-m2)
cm=as.vector(cm)
cs=s11-s12%*%s22_inv%*%s21
cs=as.matrix(cs)
#b)
cx=t(mvrnorm(n,cm,cs))
#head(cx)
R=cov2cor(cs)
cm_hat=rowMeans(cx)
cs_hat=cov(t(cx))
cr_hat=cor(t(cx))
cat("the population mean is\n");print(cm)
cat("the sample mean is\n");print(cm_hat)
cat("the population vcm is\n");print(cs)
cat("the sample vcm is\n");print(cs_hat)
cat("the correlation matrix is\n");print(R)
cat("the sample correlation matrix is\n");print(cr_hat)

```
Q.3
```{r}
library(MASS)
#a)
set.seed(123)
m=c(9.47,25.56,13.25,1.44,27.29,8.80)
S=matrix(c(2.57,0.85,1.56,1.79,1.33,0.42,
           0.85,37.00,3.34,13.47,7.59,0.52,
           1.56,3.34,8.44,5.77,2,0.5,
           1.79,13.47,5.77,34.01,10.50,1.77,
           1.33,7.59,2,10.50,23.01,3.43,
           0.42,0.52,0.50,1.77,3.43,4.59),nrow = 6,byrow = T)
p=6
q=3
n=150

x2=c(2.15,2.50,3.50)
x1_indices=c(2,4,6)
x2_indices=c(1,3,5)
m1=m[x1_indices]
m2=m[x2_indices]
s11=S[x1_indices,x1_indices]
s12=S[x1_indices,x2_indices]
s21=S[x2_indices,x1_indices]
s22=S[x2_indices,x2_indices]
s22_inv=solve(s22)

cm=m1+s12%*%s22_inv%*%(x2-m2)
cm=as.vector(cm)
cs=s11-s12%*%s22_inv%*%s21
cs=as.matrix(cs)
#b)
cx=t(mvrnorm(n,cm,cs))
#head(cx)
R=cov2cor(cs)
cm_hat=rowMeans(cx)
cs_hat=cov(t(cx))
cr_hat=cor(t(cx))

cat("the population mean is\n");print(cm)
cat("the sample mean is\n");print(cm_hat)
cat("the population vcm is\n");print(cs)
cat("the sample vcm is\n");print(cs_hat)
cat("the correlation matrix is\n");print(R)
cat("the sample vcm is\n");print(cr_hat)

```
```{r}
#c and d
s11_inv=solve(s11)
x1=c(4.5,3.5,2.5)
cm_1=m2+s21%*%s11_inv%*%(x1-m1)
cs_1=s22-s21%*%s11_inv%*%s12
cx_1=t(mvrnorm(n,cm_1,cs_1))
#head(cx)
R=cov2cor(cs_1)
cm_hat_1=rowMeans(cx_1)
cs_hat_1=cov(t(cx_1))
cr_hat_1=cor(t(cx_1))

cat("the population mean is\n");print(cm_1)
cat("the sample mean is\n");print(cm_hat_1)
cat("the population vcm is\n");print(cs_1)
cat("the sample vcm is\n");print(cs_hat_1)
cat("the correlation matrix is\n");print(R)
cat("the sample vcm is\n");print(cr_hat_1)


```


