---
title: "topic_6:classification and linear discriminant analysis "
author: "shubhangi jadhav_2405"
date: "2025-09-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Q.2)
```{r}
library(readxl)
fish_data=t(read_excel("C:\\Users\\shubh\\OneDrive\\Desktop\\ST-415-515\\fish.xlsx"))
#View(fish_data)
X=fish_data[,1:50]
Y=fish_data[,51:100]
p=nrow(fish_data)
n=ncol(fish_data)
n1=ncol(X)
n2=ncol(Y)
xbar=rowMeans(X); ybar=rowMeans(Y) 
s1=cov(t(X));     s2=cov(t(Y))
S_plooed=((n1-1)*s1)+((n2-1)*s2)/(n-2)

d=solve(S_plooed)%*%(xbar-ybar)
K=(1/2)%*%(t(xbar-ybar))%*%solve(S_plooed)%*%(xbar+ybar)
C1=t(d)%*%X>as.numeric(K)
C2=t(d)%*%Y<as.numeric(K)

n2_2=sum(C2);  n2_1=n2-n2_2
n1_1=sum(C1);  n1_2=n1-n1_1
p1_2=n1_2/n2;
p2_1=n2_1/n1;
mp=1-(n1_2+n2_1)/n;
n_mc=n2_1+n1_2;
print(mp)   #probability of misclasification

x1=c(100.78,140)
t(d)%*%x1
ifelse(t(d)%*%x1>as.numeric(K),"Alaska","Canada")
```
Q.3
```{r}
rm(list=ls())
X=t(iris[51:100,1:4])
Y=t(iris[101:150,1:4])
n1=ncol(X)
n2=ncol(Y)
n=n1 + n2
p=nrow(X)
xbar=rowMeans(X);  ybar=rowMeans(Y)
S1 <- cov(t(X));   S2 <- cov(t(Y))
S_pooled=((n1-1)*S1+(n2-1)*S2)/(n1+n2-2)
d=solve(S_pooled)%*%(xbar-ybar)
k=(1/2)%*%(t(xbar-ybar))%*%solve(S_pooled)%*%(xbar+ybar)

scoresX<-as.numeric(t(d)%*%X)
scoresY<-as.numeric(t(d)%*%Y)

predX<-ifelse(scoresX>as.vector(k),"setosa","versicolor")
predY<-ifelse(scoresY>as.vector(k),"setosa","versicolor")

# Step 9: Confusion matrix
cm<-matrix(0, 2, 2,dimnames=list(Actual=c("setosa","versicolor"),
                                 Predicted=c("setosa","versicolor")))
cm["setosa",]<-table(factor(predX, levels=c("setosa","versicolor")))
cm["versicolor",]<-table(factor(predY, levels=c("setosa","versicolor")))
print("Confusion Matrix:")
print(cm)

accuracy<-sum(diag(cm))/sum(cm) #Accuracy
misclass_prob <-1-accuracy      #misclassification probability
cat("\nAccuracy =", accuracy, "\n")
cat("Estimated misclassification probability =", misclass_prob, "\n")

# Step 11: Mahalanobis squared distance between group means
D2 <-t(xbar-ybar)%*%solve(S_pooled)%*%(xbar-ybar)
cat("Mahalanobis squared distance(D^2)=",D2)

```


